type Table = Record<string, string>;

const en: Table = {
  "card.name": "Power Origin",
  "card.description": "Where the house's power comes from, how the day went, what it earned.",
  "state.gridfree": "Grid-free",
  "state.importing": "From grid",
  "state.unknown": "No data",
  "ring.caption_autarky": "OWN POWER",
  "ring.caption_house": "HOUSE",
  "ring.caption_surplus": "AVAILABLE",
  "ring.caption_production": "PRODUCED",
  "ring.no_surplus": "NONE FREE",
  "flow.to_house": "To the house",
  "flow.to_battery": "To the battery",
  "flow.to_grid": "To the grid",
  "flow.from_solar": "From the sun",
  "flow.own": "Own power",
  "flow.from_battery": "From the battery",
  "flow.from_grid": "From the grid",
  "meter.surplus": "spare",
  "meter.charging": "to battery",
  "meter.export": "to grid",
  "meter.import": "from grid",
  "meter.discharging": "from battery",
  "meter.balanced": "balanced",
  "chart.title": "Today",
  "chart.now": "now",
  "chart.produced": "kWh produced",
  "chart.consumed": "consumed",
  "chart.forecast": "expected",
  "battery.title": "Battery",
  "battery.full": "Full",
  "battery.charging": "Charging with",
  "battery.delivering": "delivering",
  "battery.full_at": "Full at",
  "battery.lasts_until": "Lasts until",
  "battery.until_sunrise": "Lasts until sunrise",
  "battery.remaining": "left",
  "battery.stored": "stored",
  "battery.resting": "Resting",
  "today.earned": "€ earned",
  "today.paid": "€ paid",
  "today.exported_money": "exported",
  "today.imported_money": "imported",
  "stat.peak": "Peak",
  "stat.autarky": "Self-supplied",
  "stat.export": "Exported",
  "stat.import": "From grid",
  "stat.solar": "Produced",
  "stat.house": "Used",
  "stat.forecast": "Still expected",
  "error.no_house": "Set the house consumption sensor.",
  "editor.title": "Title",
  "editor.text_scale": "Text size",
  "editor.help_title": "Name it after your system. Left empty the card shows no heading.",
  "editor.help_text_scale": "1.2 or so for a tablet read from across the room.",
  "editor.entities": "Entities",
  "editor.house": "House consumption",
  "editor.solar": "Solar power",
  "editor.battery": "Battery power",
  "editor.battery_soc": "Battery charge",
  "editor.grid": "Grid power",
  "editor.solar_today": "Produced today",
  "editor.house_today": "Used today",
  "editor.export_today": "Exported today",
  "editor.import_today": "Imported today",
  "editor.forecast": "Forecast remaining",
  "editor.cost_today": "Balance today",
  "editor.cost_export_today": "Export revenue today",
  "editor.cost_import_today": "Import cost today",
  "editor.price_import": "Import price",
  "editor.price_export": "Export price",
  "editor.sections": "Blocks",
  "editor.section_ring": "Ring",
  "editor.section_chart": "Day chart",
  "editor.section_battery": "Battery",
  "editor.section_today": "Today",
  "editor.battery_settings": "Battery settings",
  "editor.capacity": "Capacity (Wh)",
  "editor.reserve": "Reserve (%)",
  "editor.style": "Style",
  "editor.style_segments": "Segments",
  "editor.style_solid": "Solid",
  "editor.style_bar": "Bar, no casing",
  "editor.segments": "Number of segments",
  "editor.help_segments": "Zero draws one per kilowatt-hour, so the blocks can be counted.",
  "editor.runtime": "Show remaining time",
  "editor.runtime_window": "Averaging window (min)",
  "editor.battery_invert": "Battery: positive means charging",
  "editor.grid_invert": "Grid: positive means export",
  "editor.ring_settings": "Ring settings",
  "editor.center": "Centre value",
  "editor.center_power": "House power",
  "editor.center_autarky": "Self-supplied share",
  "editor.center_production": "What the roof produces",
  "editor.center_surplus": "Available surplus",
  "editor.layout": "Placement of the values",
  "editor.layout_auto": "Beside when there is room",
  "editor.layout_beside": "Always beside",
  "editor.layout_below": "Always below",
  "editor.caption": "Label under the number",
  "editor.help_caption": "Free, produced, own power — or the house, which the icon already names.",
  "editor.facts": "Values beside the ring",
  "editor.facts_bars": "List with bars",
  "editor.facts_plain": "Plain list",
  "editor.facts_inline": "One line",
  "editor.facts_none": "Hidden",
  "editor.meter": "Direction meter",
  "editor.meter_scale": "Full deflection up (kW)",
  "editor.meter_scale_draw": "Full deflection down (kW)",
  "editor.help_meter_scale_draw": "Leave at 0 to take it from the house's yearly peak. A roof's scale would make an evening invisible.",
  "editor.help_meter": "A column beside the ring: surplus rises, grid draw falls.",
  "editor.meter_target": "Worth switching on (kW)",
  "editor.help_meter_scale": "Leave at 0 to take the scale from the system's yearly peak.",
  "editor.help_meter_target": "The column stays held back until this much is spare. Set it to your largest appliance.",
  "editor.chart_settings": "Day chart settings",
  "editor.consumption": "Show consumption line",
  "editor.show_forecast": "Show forecast",
  "editor.chart_height": "Chart height",
  "editor.chart_area": "Curve",
  "editor.chart_bars": "Hourly bars",
  "editor.today_settings": "Today settings",
  "editor.money": "Show money",
  "editor.breakdown": "Split the balance",
  "editor.origin_bar": "Day bar by origin",
  "editor.battery_out_today": "Battery output today",
  "editor.help_origin_bar": "Where the day's consumption came from. Without a battery output sensor it splits into own power and grid.",
  "editor.stats": "Values shown",
  "editor.help_capacity": "Usable capacity of the battery in watt-hours.",
  "editor.help_runtime": "The remaining time is averaged over this many minutes so a kettle does not move it.",
  "editor.help_house": "The only required entity. Everything else fills in a block when set."
};

const de: Table = {
  "card.name": "Power Origin",
  "card.description": "Woher der Strom im Haus kommt, wie der Tag lief, was er gebracht hat.",
  "state.gridfree": "Autark",
  "state.importing": "Netzbezug",
  "state.unknown": "Keine Daten",
  "ring.caption_autarky": "EIGENSTROM",
  "ring.caption_house": "HAUS",
  "ring.caption_surplus": "FREI",
  "ring.caption_production": "ERZEUGT",
  "ring.no_surplus": "NICHTS FREI",
  "flow.to_house": "Ins Haus",
  "flow.to_battery": "In den Speicher",
  "flow.to_grid": "Ins Netz",
  "flow.from_solar": "Aus der Sonne",
  "flow.own": "Eigenstrom",
  "flow.from_battery": "Aus dem Speicher",
  "flow.from_grid": "Aus dem Netz",
  "meter.surplus": "Überschuss",
  "meter.charging": "in den Speicher",
  "meter.export": "ins Netz",
  "meter.import": "aus dem Netz",
  "meter.discharging": "aus dem Speicher",
  "meter.balanced": "ausgeglichen",
  "chart.title": "Heute",
  "chart.now": "jetzt",
  "chart.produced": "kWh erzeugt",
  "chart.consumed": "verbraucht",
  "chart.forecast": "erwartet",
  "battery.title": "Speicher",
  "battery.full": "Voll",
  "battery.charging": "lädt mit",
  "battery.delivering": "liefert",
  "battery.full_at": "Voll um",
  "battery.lasts_until": "Reicht bis",
  "battery.until_sunrise": "Reicht bis Sonnenaufgang",
  "battery.remaining": "übrig",
  "battery.stored": "gespeichert",
  "battery.resting": "Bereit",
  "today.earned": "€ verdient",
  "today.paid": "€ gezahlt",
  "today.exported_money": "eingespeist",
  "today.imported_money": "bezogen",
  "stat.peak": "Spitze",
  "stat.autarky": "Autarkie",
  "stat.export": "Eingespeist",
  "stat.import": "Netz",
  "stat.solar": "Erzeugt",
  "stat.house": "Verbraucht",
  "stat.forecast": "Noch erwartet",
  "error.no_house": "Bitte den Sensor für den Hausverbrauch angeben.",
  "editor.title": "Titel",
  "editor.text_scale": "Textgröße",
  "editor.help_title": "Nach der Anlage benennen. Leer gelassen zeigt die Karte keine Überschrift.",
  "editor.help_text_scale": "Etwa 1,2 für ein Tablet, das man aus einigen Metern liest.",
  "editor.entities": "Entitäten",
  "editor.house": "Hausverbrauch",
  "editor.solar": "PV-Leistung",
  "editor.battery": "Speicherleistung",
  "editor.battery_soc": "Ladestand",
  "editor.grid": "Netzleistung",
  "editor.solar_today": "Heute erzeugt",
  "editor.house_today": "Heute verbraucht",
  "editor.export_today": "Heute eingespeist",
  "editor.import_today": "Heute bezogen",
  "editor.forecast": "Prognose Rest",
  "editor.cost_today": "Tagesbilanz",
  "editor.cost_export_today": "Erlös Einspeisung heute",
  "editor.cost_import_today": "Kosten Netzbezug heute",
  "editor.price_import": "Bezugspreis",
  "editor.price_export": "Einspeisepreis",
  "editor.sections": "Blöcke",
  "editor.section_ring": "Ring",
  "editor.section_chart": "Tagesverlauf",
  "editor.section_battery": "Speicher",
  "editor.section_today": "Heute",
  "editor.battery_settings": "Speicher-Einstellungen",
  "editor.capacity": "Kapazität (Wh)",
  "editor.reserve": "Reserve (%)",
  "editor.style": "Darstellung",
  "editor.style_segments": "Segmente",
  "editor.style_solid": "Durchgehend",
  "editor.style_bar": "Balken ohne Gehäuse",
  "editor.segments": "Anzahl Segmente",
  "editor.help_segments": "Null zeichnet eines je Kilowattstunde — dann sind die Blöcke abzählbar.",
  "editor.runtime": "Restzeit anzeigen",
  "editor.runtime_window": "Mittelung (Minuten)",
  "editor.battery_invert": "Speicher: positiv bedeutet laden",
  "editor.grid_invert": "Netz: positiv bedeutet einspeisen",
  "editor.ring_settings": "Ring-Einstellungen",
  "editor.center": "Wert in der Mitte",
  "editor.center_power": "Hausverbrauch",
  "editor.center_autarky": "Eigenversorgung",
  "editor.center_production": "Erzeugung des Dachs",
  "editor.center_surplus": "Freier Überschuss",
  "editor.layout": "Anordnung der Werte",
  "editor.layout_auto": "Daneben, wenn Platz ist",
  "editor.layout_beside": "Immer daneben",
  "editor.layout_below": "Immer darunter",
  "editor.caption": "Beschriftung unter der Zahl",
  "editor.help_caption": "Frei, erzeugt, Eigenstrom — oder das Haus, das schon das Symbol benennt.",
  "editor.facts": "Werte neben dem Ring",
  "editor.facts_bars": "Liste mit Balken",
  "editor.facts_plain": "Schlichte Liste",
  "editor.facts_inline": "Einzeilig",
  "editor.facts_none": "Ausgeblendet",
  "editor.meter": "Richtungsanzeige",
  "editor.meter_scale": "Vollausschlag oben (kW)",
  "editor.meter_scale_draw": "Vollausschlag unten (kW)",
  "editor.help_meter_scale_draw": "Bei 0 aus der Jahresspitze des Hauses. Mit der Dachskala wäre ein Abend unsichtbar.",
  "editor.help_meter": "Eine Säule neben dem Ring: Überschuss steigt, Netzbezug fällt.",
  "editor.meter_target": "Lohnt sich ab (kW)",
  "editor.help_meter_scale": "Bei 0 nimmt sie den Maßstab aus der Jahresspitze der Anlage.",
  "editor.help_meter_target": "Bis zu diesem Überschuss bleibt die Säule zurückhaltend. Auf den größten Verbraucher stellen.",
  "editor.chart_settings": "Tagesverlauf-Einstellungen",
  "editor.consumption": "Verbrauchslinie anzeigen",
  "editor.show_forecast": "Prognose anzeigen",
  "editor.chart_height": "Höhe des Diagramms",
  "editor.chart_area": "Kurve",
  "editor.chart_bars": "Stundenbalken",
  "editor.today_settings": "Heute-Einstellungen",
  "editor.money": "Geld anzeigen",
  "editor.breakdown": "Bilanz aufschlüsseln",
  "editor.origin_bar": "Tagesbalken nach Herkunft",
  "editor.battery_out_today": "Speicherabgabe heute",
  "editor.help_origin_bar": "Woher der Tagesverbrauch kam. Ohne Sensor für die Speicherabgabe teilt er sich in Eigenstrom und Netz.",
  "editor.stats": "Angezeigte Werte",
  "editor.help_capacity": "Nutzbare Kapazität des Speichers in Wattstunden.",
  "editor.help_runtime": "Die Restzeit wird über so viele Minuten gemittelt, damit ein Wasserkocher sie nicht verreißt.",
  "editor.help_house": "Die einzige Pflichtangabe. Alles andere blendet einen Block ein, sobald es gesetzt ist."
};

export const TRANSLATIONS: Record<string, Table> = { en, de };

export function baseLanguage(locale: string | undefined): string {
  const tag = String(locale ?? "").toLowerCase();
  const base = tag.split(/[-_]/)[0];
  return base in TRANSLATIONS ? base : "en";
}

export function localize(key: string, locale?: string): string {
  const table = TRANSLATIONS[baseLanguage(locale)];
  return table[key] ?? en[key] ?? key;
}
