type Table = Record<string, string>;

const en: Table = {
  "card.name": "Power Origin",
  "card.description": "Where the house's power comes from, how the day went, what it earned.",
  "state.gridfree": "Grid-free",
  "state.importing": "From grid",
  "state.unknown": "No data",
  "ring.caption_autarky": "OWN POWER",
  "ring.caption_house": "HOUSE",
  "ring.source_battery": "Battery",
  "ring.source_grid": "Grid",
  "ring.source_solar": "Sun",
  "ring.caption_surplus": "AVAILABLE",
  "ring.caption_production": "PRODUCED",
  "ring.no_surplus": "NONE FREE",
  "flow.to_house": "To the house",
  "flow.to_battery": "To the battery",
  "flow.to_grid": "To the grid",
  "flow.from_solar": "From the sun",
  "flow.own": "Own power",
  "flow.from_battery": "From the battery",
  "flow.from_grid": "From the grid",
  "meter.surplus": "spare",
  "editor.meter_scope": "What the column measures",
  "editor.meter_scope_grid": "Grid only",
  "editor.meter_scope_all": "Grid and battery",
  "editor.help_meter_scope": "Grid only shows what crosses the meter: import downwards, export upwards. Grid and battery also counts charging as surplus and discharging as draw.",
  "meter.quiet": "no grid exchange",
  "meter.draw": "drawn",
  "meter.charging": "to battery",
  "meter.export": "to grid",
  "meter.import": "from grid",
  "meter.discharging": "from battery",
  "meter.balanced": "balanced",
  "chart.title": "Today",
  "chart.now": "now",
  "chart.produced": "kWh produced",
  "chart.consumed": "consumed",
  "chart.forecast": "expected",
  "battery.title": "Battery",
  "battery.full": "Full",
  "battery.charging": "Charging with",
  "battery.delivering": "delivering",
  "battery.full_at": "Full at",
  "battery.lasts_until": "Lasts until",
  "battery.until_sunrise": "Lasts until sunrise",
  "battery.remaining": "left",
  "battery.stored": "stored",
  "battery.resting": "Resting",
  "today.earned": "€ earned",
  "today.paid": "€ paid",
  "today.exported_money": "exported",
  "today.imported_money": "imported",
  "stat.peak": "Peak",
  "stat.autarky": "Self-supplied",
  "stat.export": "Exported",
  "stat.import": "From grid",
  "stat.solar": "Produced",
  "stat.house": "Used",
  "stat.forecast": "Still expected",
  "stat.amortisation": "Paid off",
  "error.no_house": "Set the house consumption sensor.",
  "editor.title": "Title",
  "editor.chip": "State chip",
  "editor.chip_gridfree": "Only while off the grid",
  "editor.chip_always": "Always",
  "editor.chip_never": "Never",
  "editor.help_chip": "The word in the corner. Only while off the grid keeps it for the state worth noticing; always also shows it when the grid is carrying part of the house.",
  "editor.text_scale": "Text size",
  "editor.help_title": "Name it after your system. Left empty the card shows no heading.",
  "editor.help_text_scale": "1.2 or so for a tablet read from across the room.",
  "editor.entities": "Entities",
  "editor.house": "House consumption",
  "editor.solar": "Solar power",
  "editor.battery": "Battery power",
  "editor.battery_soc": "Battery charge",
  "editor.grid": "Grid power",
  "editor.solar_today": "Produced today",
  "editor.house_today": "Used today",
  "editor.export_today": "Exported today",
  "editor.import_today": "Imported today",
  "editor.forecast": "Forecast remaining",
  "editor.help_cost_today": "Leave empty and it is the revenue less the cost, worked out here.",
  "editor.help_cost_sides": "Leave empty and it is the price times the energy, worked out here. That only holds on a fixed tariff — on a spot tariff let an integration accumulate it.",
  "editor.help_price": "Only needed to work the two money figures out; a fixed price per kilowatt hour.",
  "editor.cost_today": "Balance today",
  "editor.cost_export_today": "Export revenue today",
  "editor.cost_import_today": "Import cost today",
  "editor.price_import": "Import price",
  "editor.price_export": "Export price",
  "editor.sections": "Blocks",
  "editor.section_ring": "Ring",
  "editor.section_chart": "Day chart",
  "editor.section_battery": "Battery",
  "editor.section_today": "Today",
  "editor.battery_settings": "Battery settings",
  "editor.capacity": "Capacity (Wh)",
  "editor.reserve": "Reserve (%)",
  "editor.style": "Style",
  "editor.style_segments": "Segments",
  "editor.style_solid": "Solid",
  "editor.style_bar": "Bar, no casing",
  "editor.segments": "Number of segments",
  "editor.help_segments": "Zero draws one per kilowatt-hour, so the blocks can be counted.",
  "editor.runtime": "Show remaining time",
  "editor.runtime_window": "Averaging window (min)",
  "editor.battery_invert": "Battery: positive means charging",
  "editor.grid_invert": "Grid: positive means export",
  "editor.ring_settings": "Ring settings",
  "editor.size": "Size of ring and column",
  "editor.size_auto": "Automatic",
  "editor.size_s": "Small",
  "editor.size_m": "Medium",
  "editor.size_l": "Large",
  "editor.help_size": "Automatic keeps them small beside a list and lets them grow when they have the card to themselves. The fixed sizes also set the height of the block.",
  "editor.meter_settings": "Column settings",
  "editor.center": "Centre value",
  "editor.help_center": "With the meter beside it, keep the ring on the house: the meter already splits the surplus.",
  "editor.center_dark": "Centre value without sun",
  "editor.help_center_dark": "Production and surplus have nothing to say at night, so this takes over.",
  "editor.center_power": "House power",
  "editor.center_autarky": "Self-supplied share",
  "editor.center_production": "What the roof produces",
  "editor.center_surplus": "Available surplus",
  "editor.layout": "Placement of the values",
  "editor.layout_auto": "Beside when there is room",
  "editor.layout_beside": "Always beside",
  "editor.layout_below": "Always below",
  "editor.caption": "Label under the number",
  "editor.help_caption": "Free, produced, own power — or the house, which the icon already names.",
  "editor.facts": "Values beside the ring",
  "editor.facts_bars": "List with bars",
  "editor.facts_plain": "Plain list",
  "editor.facts_inline": "One line",
  "editor.facts_none": "Hidden",
  "editor.meter": "Direction meter",
  "editor.meter_scale": "Full deflection up (kW · 0 = automatic)",
  "editor.meter_scale_draw": "Full deflection down (kW · 0 = automatic)",
  "editor.help_meter_scale_draw": "Zero uses three kilowatts, the band a house lives in. Raise it if a wallbox or heat pump is on this meter.",
  "editor.help_meter": "A column beside the ring: surplus rises, grid draw falls.",
  "editor.meter_target": "Worth switching on (kW · 0 = off)",
  "editor.meter_steps": "Blocks per direction",
  "editor.meter_style": "Column style",
  "editor.meter_bar": "Continuous",
  "editor.meter_blocks": "Blocks",
  "editor.help_meter_scale": "Leave at 0 to take the scale from the system's yearly peak.",
  "editor.help_meter_target": "Only you know what is worth starting, so this is not derived: set it to your largest appliance, or leave it off.",
  "editor.chart_settings": "Day chart settings",
  "editor.consumption": "Show consumption line",
  "editor.show_forecast": "Show forecast",
  "editor.chart_height": "Chart height",
  "editor.chart_area": "Curve",
  "editor.chart_bars": "Hourly bars",
  "editor.today_settings": "Today settings",
  "editor.money": "Show money",
  "editor.breakdown": "Split the balance",
  "editor.amortisation_corner": "Paid off, in the corner",
  "editor.origin_bar": "Day bar by origin",
  "editor.battery_out_today": "Battery output today",
  "editor.amortisation": "Paid off so far",
  "editor.help_origin_bar": "Where the day's consumption came from. Without a battery output sensor it splits into own power and grid.",
  "editor.stats": "Values shown",
  "editor.help_capacity": "Usable capacity of the battery in watt-hours.",
  "editor.help_runtime": "The remaining time is averaged over this many minutes so a kettle does not move it.",
  "editor.help_house": "The only required entity. Everything else fills in a block when set."
};

const de: Table = {
  "card.name": "Power Origin",
  "card.description": "Woher der Strom im Haus kommt, wie der Tag lief, was er gebracht hat.",
  "state.gridfree": "Autark",
  "state.importing": "Netzbezug",
  "state.unknown": "Keine Daten",
  "ring.caption_autarky": "EIGENSTROM",
  "ring.caption_house": "HAUS",
  "ring.source_battery": "Speicher",
  "ring.source_grid": "Netz",
  "ring.source_solar": "Sonne",
  "ring.caption_surplus": "FREI",
  "ring.caption_production": "ERZEUGT",
  "ring.no_surplus": "NICHTS FREI",
  "flow.to_house": "Ins Haus",
  "flow.to_battery": "In den Speicher",
  "flow.to_grid": "Ins Netz",
  "flow.from_solar": "Aus der Sonne",
  "flow.own": "Eigenstrom",
  "flow.from_battery": "Aus dem Speicher",
  "flow.from_grid": "Aus dem Netz",
  "meter.surplus": "Überschuss",
  "editor.meter_scope": "Was die Säule misst",
  "editor.meter_scope_grid": "Nur Netz",
  "editor.meter_scope_all": "Netz und Speicher",
  "editor.help_meter_scope": "Nur Netz zeigt, was über den Zähler geht: Bezug nach unten, Einspeisung nach oben. Netz und Speicher zählt zusätzlich das Laden als Überschuss und das Entladen als Bezug.",
  "meter.quiet": "kein Netzaustausch",
  "meter.draw": "Entnahme",
  "meter.charging": "in den Speicher",
  "meter.export": "ins Netz",
  "meter.import": "aus dem Netz",
  "meter.discharging": "aus dem Speicher",
  "meter.balanced": "ausgeglichen",
  "chart.title": "Heute",
  "chart.now": "jetzt",
  "chart.produced": "kWh erzeugt",
  "chart.consumed": "verbraucht",
  "chart.forecast": "erwartet",
  "battery.title": "Speicher",
  "battery.full": "Voll",
  "battery.charging": "lädt mit",
  "battery.delivering": "liefert",
  "battery.full_at": "Voll um",
  "battery.lasts_until": "Reicht bis",
  "battery.until_sunrise": "Reicht bis Sonnenaufgang",
  "battery.remaining": "übrig",
  "battery.stored": "gespeichert",
  "battery.resting": "Bereit",
  "today.earned": "€ verdient",
  "today.paid": "€ gezahlt",
  "today.exported_money": "eingespeist",
  "today.imported_money": "bezogen",
  "stat.peak": "Spitze",
  "stat.autarky": "Autarkie",
  "stat.export": "Eingespeist",
  "stat.import": "Netz",
  "stat.solar": "Erzeugt",
  "stat.house": "Verbraucht",
  "stat.forecast": "Noch erwartet",
  "stat.amortisation": "Amortisiert",
  "error.no_house": "Bitte den Sensor für den Hausverbrauch angeben.",
  "editor.title": "Titel",
  "editor.chip": "Status-Chip",
  "editor.chip_gridfree": "Nur wenn netzfrei",
  "editor.chip_always": "Immer",
  "editor.chip_never": "Nie",
  "editor.help_chip": "Das Wort in der Ecke. Nur wenn netzfrei behält es für den Zustand, der auffallen soll; immer zeigt es auch, wenn das Netz mitträgt.",
  "editor.text_scale": "Textgröße",
  "editor.help_title": "Nach der Anlage benennen. Leer gelassen zeigt die Karte keine Überschrift.",
  "editor.help_text_scale": "Etwa 1,2 für ein Tablet, das man aus einigen Metern liest.",
  "editor.entities": "Entitäten",
  "editor.house": "Hausverbrauch",
  "editor.solar": "PV-Leistung",
  "editor.battery": "Speicherleistung",
  "editor.battery_soc": "Ladestand",
  "editor.grid": "Netzleistung",
  "editor.solar_today": "Heute erzeugt",
  "editor.house_today": "Heute verbraucht",
  "editor.export_today": "Heute eingespeist",
  "editor.import_today": "Heute bezogen",
  "editor.forecast": "Prognose Rest",
  "editor.help_cost_today": "Leer lassen, dann ist es Erlös minus Kosten, hier gerechnet.",
  "editor.help_cost_sides": "Leer lassen, dann ist es Preis mal Energie, hier gerechnet. Das stimmt nur bei einem Fixtarif — bei Spot lass es eine Integration mitlaufend summieren.",
  "editor.help_price": "Nur nötig, um die beiden Geldwerte auszurechnen; ein fester Preis je Kilowattstunde.",
  "editor.cost_today": "Tagesbilanz",
  "editor.cost_export_today": "Erlös Einspeisung heute",
  "editor.cost_import_today": "Kosten Netzbezug heute",
  "editor.price_import": "Bezugspreis",
  "editor.price_export": "Einspeisepreis",
  "editor.sections": "Blöcke",
  "editor.section_ring": "Ring",
  "editor.section_chart": "Tagesverlauf",
  "editor.section_battery": "Speicher",
  "editor.section_today": "Heute",
  "editor.battery_settings": "Speicher-Einstellungen",
  "editor.capacity": "Kapazität (Wh)",
  "editor.reserve": "Reserve (%)",
  "editor.style": "Darstellung",
  "editor.style_segments": "Segmente",
  "editor.style_solid": "Durchgehend",
  "editor.style_bar": "Balken ohne Gehäuse",
  "editor.segments": "Anzahl Segmente",
  "editor.help_segments": "Null zeichnet eines je Kilowattstunde — dann sind die Blöcke abzählbar.",
  "editor.runtime": "Restzeit anzeigen",
  "editor.runtime_window": "Mittelung (Minuten)",
  "editor.battery_invert": "Speicher: positiv bedeutet laden",
  "editor.grid_invert": "Netz: positiv bedeutet einspeisen",
  "editor.ring_settings": "Ring-Einstellungen",
  "editor.size": "Größe von Ring und Säule",
  "editor.size_auto": "Automatisch",
  "editor.size_s": "Klein",
  "editor.size_m": "Mittel",
  "editor.size_l": "Groß",
  "editor.help_size": "Automatisch hält sie neben einer Liste klein und lässt sie wachsen, wenn sie die Karte für sich haben. Die festen Größen bestimmen auch die Höhe des Blocks.",
  "editor.meter_settings": "Säulen-Einstellungen",
  "editor.center": "Wert in der Mitte",
  "editor.help_center": "Mit Säule daneben den Ring beim Haus lassen — den Überschuss teilt die Säule schon auf.",
  "editor.center_dark": "Wert in der Mitte ohne Sonne",
  "editor.help_center_dark": "Erzeugung und Überschuss haben nachts nichts zu sagen — dann übernimmt dieser.",
  "editor.center_power": "Hausverbrauch",
  "editor.center_autarky": "Eigenversorgung",
  "editor.center_production": "Erzeugung des Dachs",
  "editor.center_surplus": "Freier Überschuss",
  "editor.layout": "Anordnung der Werte",
  "editor.layout_auto": "Daneben, wenn Platz ist",
  "editor.layout_beside": "Immer daneben",
  "editor.layout_below": "Immer darunter",
  "editor.caption": "Beschriftung unter der Zahl",
  "editor.help_caption": "Frei, erzeugt, Eigenstrom — oder das Haus, das schon das Symbol benennt.",
  "editor.facts": "Werte neben dem Ring",
  "editor.facts_bars": "Liste mit Balken",
  "editor.facts_plain": "Schlichte Liste",
  "editor.facts_inline": "Einzeilig",
  "editor.facts_none": "Ausgeblendet",
  "editor.meter": "Richtungsanzeige",
  "editor.meter_scale": "Vollausschlag oben (kW · 0 = automatisch)",
  "editor.meter_scale_draw": "Vollausschlag unten (kW · 0 = automatisch)",
  "editor.help_meter_scale_draw": "Bei 0 gelten drei Kilowatt, der Bereich, in dem ein Haus lebt. Höher stellen, wenn Wallbox oder Wärmepumpe mitzählen.",
  "editor.help_meter": "Eine Säule neben dem Ring: Überschuss steigt, Netzbezug fällt.",
  "editor.meter_target": "Lohnt sich ab (kW · 0 = aus)",
  "editor.meter_steps": "Blöcke je Richtung",
  "editor.meter_style": "Darstellung der Säule",
  "editor.meter_bar": "Stufenlos",
  "editor.meter_blocks": "Blöcke",
  "editor.help_meter_scale": "Bei 0 nimmt sie den Maßstab aus der Jahresspitze der Anlage.",
  "editor.help_meter_target": "Was sich zu starten lohnt, weißt nur du — das lässt sich nicht ableiten. Auf den größten Verbraucher stellen oder aus lassen.",
  "editor.chart_settings": "Tagesverlauf-Einstellungen",
  "editor.consumption": "Verbrauchslinie anzeigen",
  "editor.show_forecast": "Prognose anzeigen",
  "editor.chart_height": "Höhe des Diagramms",
  "editor.chart_area": "Kurve",
  "editor.chart_bars": "Stundenbalken",
  "editor.today_settings": "Heute-Einstellungen",
  "editor.money": "Geld anzeigen",
  "editor.breakdown": "Bilanz aufschlüsseln",
  "editor.amortisation_corner": "Amortisiert, in der Ecke",
  "editor.origin_bar": "Tagesbalken nach Herkunft",
  "editor.battery_out_today": "Speicherabgabe heute",
  "editor.amortisation": "Bisher amortisiert",
  "editor.help_origin_bar": "Woher der Tagesverbrauch kam. Ohne Sensor für die Speicherabgabe teilt er sich in Eigenstrom und Netz.",
  "editor.stats": "Angezeigte Werte",
  "editor.help_capacity": "Nutzbare Kapazität des Speichers in Wattstunden.",
  "editor.help_runtime": "Die Restzeit wird über so viele Minuten gemittelt, damit ein Wasserkocher sie nicht verreißt.",
  "editor.help_house": "Die einzige Pflichtangabe. Alles andere blendet einen Block ein, sobald es gesetzt ist."
};

export const TRANSLATIONS: Record<string, Table> = { en, de };

export function baseLanguage(locale: string | undefined): string {
  const tag = String(locale ?? "").toLowerCase();
  const base = tag.split(/[-_]/)[0];
  return base in TRANSLATIONS ? base : "en";
}

export function localize(key: string, locale?: string): string {
  const table = TRANSLATIONS[baseLanguage(locale)];
  return table[key] ?? en[key] ?? key;
}
