type Table = Record<string, string>;
const en: Table = {
  "card.name": "Power Origin",
  "card.description": "Where the house's power comes from, how the day went, what it earned.",
  "state.gridfree": "Grid-free",
  "state.importing": "From grid",
  "state.unknown": "No data",
  "state.unreachable": "House sensor not reporting:",
  "ring.caption_autarky": "SELF-SUPPLIED",
  "ring.caption_house": "HOUSE",
  "ring.caption_until": "until",
  "ring.source_battery": "Battery",
  "ring.source_grid": "Grid",
  "ring.source_solar": "Sun",
  "ring.caption_surplus": "AVAILABLE",
  "ring.caption_production": "PRODUCED",
  "ring.no_surplus": "NONE FREE",
  "flow.to_house": "To the house",
  "flow.to_battery": "To the battery",
  "flow.to_grid": "To the grid",
  "flow.from_solar": "From the sun",
  "flow.own": "Own power",
  "flow.from_battery": "From the battery",
  "flow.from_grid": "From the grid",
  "meter.surplus": "spare",
  "editor.meter_scope": "What counts as surplus",
  "editor.meter_scope_grid": "Grid only",
  "editor.meter_scope_all": "Grid and battery",
  "editor.help_meter_scope": "Grid only is what crosses the meter.",
  "editor.meter_today": "Show today's extremes",
  "editor.help_meter_today": "How far the needle swung today, in both directions.",
  "editor.columns": "Columns beside the ring",
  "editor.columns_none": "None",
  "editor.columns_one": "One",
  "editor.columns_two": "Two",
  "editor.column_left": "The left column",
  "editor.column_right": "The right column",
  "editor.meter_top": "The best today, above the column",
  "editor.help_meter_top": "Without it the kilowatts never say whether this is a good moment.",
  "editor.meter_marks": "Out and in at the ends",
  "editor.help_meter_marks": "Two small arrows, so which end means which needs no reading.",
  "editor.meter_money": "Money",
  "editor.meter_load": "The house now against today’s average",
  "editor.meter_autarky": "Self-supplied now, bottom to top",
  "meter.earning": "earning now",
  "meter.costing": "costing now",
  "meter.above": "above today’s average",
  "meter.below": "below today’s average",
  "meter.usual": "an ordinary hour",
  "meter.autarky": "self-supplied now",
  "editor.center_runtime": "How long the battery lasts",
  "editor.center_money": "Money per hour (€/h)",
  "ring.caption_earning": "EARNING",
  "ring.caption_costing": "COSTING",
  "ring.caption_even": "EVEN",
  "editor.ring_dayclock": "Clock outside",
  "editor.inner_battery": "The battery charge as a thin ring",
  "editor.night": "The ring at night",
  "editor.night_countdown": "Countdown",
  "editor.help_night": "The outer ring becomes the night, filled as far as it has come.",
  "ring.to_sun": "to sunrise",
  "editor.tap": "Tapping the ring",
  "editor.tap_entity": "Opens the entity behind the figure",
  "editor.tap_cycle": "Steps the centre value on",
  "editor.help_tap": "Stepping goes through house, self-supplied and money; the ring remembers where it stopped.",
  "editor.sunrise_mark": "Sun at the sunrise level",
  "editor.help_sunrise_mark": "At night, a sun under the bar where the charge will stand at sunrise.",
  "editor.sunset_mark": "Moon at the sunset level",
  "editor.help_sunset_mark": "By day, a moon under the bar where the charge will stand at sunset, when it will not fill.",
  "editor.meter_battery": "Battery",
  "editor.meter_night": "The night",
  "editor.meter_devices": "Devices",
  "editor.meter_none": "Nothing",
  "editor.columns_scale": "Scale under the ring",
  "editor.help_columns": "The scale lays the left column flat under the ring.",
  "editor.import_switch": "Lasting draw switches the column",
  "editor.help_import_switch": "Two minutes of draw switches it, five without switches it back.",
  "meter.night": "the night",
  "meter.at_sunrise": "at sunrise",
  "meter.grid_until_sun": "the grid until sunrise",
  "editor.battery_night": "The bar at night",
  "editor.autarky_colours": "Self-supplied column in three colours",
  "editor.help_autarky_colours": "Grid below half, sun to eighty percent, battery above.",
  "editor.animate": "A wave while the battery moves",
  "editor.help_animate": "Towards the cap while charging, away from it while discharging.",
  "meter.held": "held",
  "editor.forecast_hourly": "Forecast by hour",
  "editor.help_forecast_hourly": "Solcast's Forecast Today carries them in its attributes. Several, one per roof face, are added up.",
  "editor.forecast_bars": "Expected hours as outlines",
  "editor.help_forecast_bars": "Dashed outlines; after sunset, tomorrow.",
  "editor.layers": "Grid and battery as areas",
  "editor.help_layers": "Hour by hour, under the day.",
  "editor.best_day": "The year's best day behind",
  "editor.help_best_day": "A faint line to read today against.",
  "editor.section_week": "Week",
  "week.title": "Week",
  "chart.best": "best",
  "editor.battery_in_today": "Battery input today",
  "editor.extra_flow": "Charged and given out today, with the cycles",
  "editor.curve": "The charge as a curve below",
  "editor.help_curve": "Dashed on to sunrise, or to full.",
  "battery.flow": "charged and given out",
  "editor.meter_dark": "Once the sun is down it shows",
  "editor.help_meter_dark": "What takes the column's place until sunrise.",
  "editor.same": "Unchanged",
  "editor.night_dim": "Dim at night (%)",
  "editor.help_night_dim": "The chip stays bright. For a panel on the wall.",
  "editor.extra_sunrise": "Charge at sunrise",
  "meter.range_reaches": "reaches sunrise",
  "chart.tomorrow": "tomorrow",
  "editor.forecast_tomorrow": "Forecast tomorrow",
  "meter.range_gap": "short by",
  "battery.at_sunrise": "at sunrise,",
  "meter.roof": "solar now",
  "editor.meter_roof": "What the PV makes now, against its best today",
  "meter.day": "today by hour",
  "meter.balance": "solar against house",
  "meter.spare": "solar spare",
  "meter.short": "bought in",
  "editor.meter_balance": "Solar and house now",
  "meter.quiet": "no grid exchange",
  "meter.draw": "drawn",
  "meter.charging": "to battery",
  "meter.export": "to grid",
  "meter.import": "from grid",
  "meter.discharging": "from battery",
  "meter.balanced": "balanced",
  "editor.compare": "Compare with last week",
  "editor.help_compare": "The same weekday a week ago, faintly behind today.",
  "devices.today": "today",
  "editor.mode": "Period",
  "editor.mode_now": "Now",
  "editor.mode_today": "Today",
  "editor.help_mode": "Reads the meters the Energy dashboard lists per device.",
  "editor.window": "Window (minutes)",
  "editor.help_window": "Averaged this long, so a kettle is not read as a hog.",
  "devices.title": "Where to",
  "devices.rest": "rest",
  "devices.nowhere": "no room",
  "editor.section_devices": "Devices",
  "editor.devices_settings": "Devices",
  "editor.list": "Devices (power sensors)",
  "editor.help_list": "The icon comes from the sensor in Home Assistant.",
  "editor.source": "Device list",
  "editor.source_list": "Own list",
  "editor.source_energy": "Energy dashboard",
  "editor.help_source": "Following the dashboard, a device added there shows up here within the hour.",
  "editor.devices_head": "Show the heading",
  "editor.help_devices_head": "The word and the period above the block.",
  "editor.devices_colours": "A colour per device",
  "editor.help_devices_colours": "As the Energy dashboard gives them; otherwise brightness alone.",
  "editor.devices_rows": "Rows",
  "editor.devices_band": "Band",
  "editor.devices_icons": "Icons on a grid, with a level",
  "devices.one": "device",
  "devices.many": "devices",
  "editor.top": "The biggest as a row of its own",
  "editor.help_top": "With how long it has been drawing and what it cost today.",
  "editor.spark": "A line per device, last hour",
  "editor.help_spark": "The fridge's rhythm, the heat pump's ramp, the kettle's spike.",
  "editor.device_icons": "Icons",
  "devices.since": "since",
  "editor.month": "The month beside the day",
  "editor.help_month": "Small beside the day's figure.",
  "editor.split": "Split not bought from sold",
  "editor.help_split": "How much of the day's money was not buying, and how much selling.",
  "editor.payoff_year": "The year it is paid off",
  "editor.help_payoff_year": "From the paid-off share and this year's pace.",
  "editor.investment": "What the system cost (€)",
  "editor.help_investment": "All in. Left at 0, the card reads it off the paid-off sensor.",
  "money.not_bought": "not bought",
  "money.sold": "sold",
  "editor.card_settings": "Card",
  "editor.head_settings": "Header",
  "editor.chip_shows": "The chip says",
  "editor.chip_state": "State",
  "editor.chip_autarky": "The day's self-supplied share",
  "chip.autarky": "Self-supplied",
  "editor.chip_alarm": "Lasting draw reddens the chip",
  "editor.help_chip_alarm": "After two minutes of draw the chip turns red and carries the kilowatts.",
  "editor.head_price": "The import price beside the title",
  "editor.help_head_price": "Green under the day's mean, red over it.",
  "editor.card_layout": "Shape of the card",
  "editor.layout_standard": "Standard",
  "editor.layout_wide": "Wide",
  "editor.layout_compact": "Compact",
  "editor.wide_from": "Wide from (px)",
  "editor.help_wide_from": "Narrower than this the card stacks; below 560 px in any case.",
  "editor.night_layout": "Once the sun is down",
  "editor.night_quiet": "Quiet",
  "editor.help_night_layout": "Quiet keeps the ring, the battery and one line about the day.",
  "compact.roof": "PV",
  "editor.head_sunbar": "A sun line under the title",
  "editor.help_head_sunbar": "An arc with the sun where it stands, and the moon at night.",
  "money.of": "of",
  "money.a_year": "a year at this pace",
  "editor.values": "Print the watts",
  "editor.group": "Group by",
  "editor.group_device": "Device",
  "editor.group_area": "Room",
  "editor.help_group": "By room sums the devices standing in one room, read from the device registry.",
  "editor.merge_icons": "Merge identical icons",
  "editor.help_merge_icons": "Two fridges become one icon with their sum; the names show on hover.",
  "editor.limit": "At most",
  "editor.help_limit": "Rows and band name this many and fold the rest; icons show no more than this.",
  "editor.threshold": "Named from (W)",
  "editor.help_threshold": "Anything smaller folds into the rest — otherwise nine fridges would stand there.",
  "chart.title": "Today",
  "chart.now": "now",
  "chart.roof_now": "solar now",
  "chart.produced": "kWh produced",
  "chart.consumed": "consumed",
  "chart.forecast": "expected",
  "chart.shortfall": "below forecast",
  "chart.snow": "snow on the roof?",
  "editor.reserve_line": "Mark the reserve on the bar",
  "editor.extra": "Second figure beside the bar",
  "editor.extra_none": "None",
  "editor.extra_range": "Lowest and highest today",
  "editor.extra_cycles": "Cycles today",
  "editor.extra_saved": "Not bought today",
  "editor.extra_given": "Given out today",
  "editor.help_extra": "The bar gives up width for it.",
  "battery.range": "low to high",
  "battery.cycles": "cycles",
  "battery.saved": "not bought",
  "battery.given": "given out",
  "editor.percent": "Show the charge as a figure",
  "battery.title": "Battery",
  "battery.full": "Full",
  "battery.charging": "Charging with",
  "battery.delivering": "delivering",
  "battery.full_at": "Full at",
  "battery.full_about": "Full around",
  "battery.full_between": "Full between",
  "battery.and": "and",
  "battery.not_full_today": "Not full today",
  "battery.today_up_to": "Today up to",
  "editor.full_from": "When it is full",
  "editor.full_rate": "From the charge rate right now",
  "editor.full_forecast": "From the forecast by the hour",
  "editor.help_full_from": "The rate cannot see the evening; the forecast can.",
  "editor.palette": "Colours",
  "editor.palette_standard": "Standard",
  "editor.palette_traffic": "Traffic light",
  "editor.palette_safe": "Colour-safe",
  "editor.palette_muted": "Muted",
  "editor.help_palette": "One set for the whole card. Standard: sun gold, battery green, grid blue. Traffic light: yellow, orange, red. Colour-safe: amber, blue, magenta. Muted: the same three, quieter.",
  "editor.font": "Figures",
  "editor.font_mono": "Monospace",
  "editor.font_system": "Home Assistant",
  "editor.help_font": "Monospace keeps a changing figure from shifting the line; Home Assistant's font matches the cards around it.",
  "battery.lasts_until": "Lasts until",
  "battery.at_reserve": "At the reserve",
  "battery.sunrise_tight": "Only just reaches sunrise",
  "battery.sunrise_ok": "Lasts until sunrise",
  "battery.sunrise_easy": "Past sunrise with ease",
  "battery.remaining": "left",
  "battery.stored": "stored",
  "battery.resting": "Resting",
  "today.earned": "€ earned",
  "today.paid": "€ paid",
  "today.exported_money": "exported",
  "today.imported_money": "imported",
  "stat.peak": "PV peak",
  "stat.autarky": "Self-supplied",
  "stat.export": "Exported",
  "stat.import": "From grid",
  "stat.solar": "Produced",
  "stat.house": "Used",
  "stat.forecast": "Still expected",
  "stat.amortisation": "Paid off",
  "error.no_house": "Set the house consumption sensor.",
  "editor.title": "Title",
  "editor.tap_action": "Tapping a figure",
  "editor.help_tap_action": "By default a figure opens the entity it came from.",
  "editor.chip": "State chip",
  "editor.chip_gridfree": "Only while off the grid",
  "editor.chip_always": "Always",
  "editor.chip_never": "Never",
  "editor.help_chip": "Off the grid keeps it for the state worth noticing.",
  "editor.text_scale": "Text size",
  "editor.help_title": "Name it after your system. Left empty the card shows no heading.",
  "editor.help_text_scale": "1.2 or so for a tablet read from across the room.",        "editor.entities": "Entities",
  "editor.house": "House consumption",
  "editor.solar": "Solar power",
  "editor.battery": "Battery power",
  "editor.battery_soc": "Battery charge",
  "editor.grid": "Grid power",
  "editor.solar_today": "Produced today",
  "editor.house_today": "Used today",
  "editor.export_today": "Exported today",
  "editor.import_today": "Imported today",
  "editor.forecast": "Forecast remaining",
  "editor.help_cost_today": "Leave empty and it is the revenue less the cost, worked out here.",
  "editor.help_cost_sides": "Left empty it is price times energy, which holds on a fixed tariff.",
  "editor.help_price": "A fixed price per kilowatt hour.",
  "editor.cost_today": "Balance today",
  "editor.cost_export_today": "Export revenue today",
  "editor.cost_import_today": "Import cost today",
  "editor.price_import": "Import price",
  "editor.price_export": "Export price",
  "editor.sections": "Blocks",
  "editor.order": "Order",
  "editor.help_order": "Pick, then drag into place; the rest follow.",
  "editor.section_ring": "Ring",
  "editor.section_chart": "Day chart",
  "editor.section_battery": "Battery",
  "editor.section_today": "Today",
  "editor.battery_settings": "Battery",
  "editor.capacity": "Capacity (Wh)",
  "editor.reserve": "Reserve (%)",
  "editor.style": "Style",
  "editor.style_segments": "Segments",
  "editor.style_solid": "Solid",
  "editor.style_bar": "Bar, no casing",
  "editor.segments": "Number of segments",
  "editor.help_segments": "Zero draws one per kilowatt-hour, so the blocks can be counted.",
  "editor.runtime": "Show remaining time",
  "editor.runtime_window": "Averaging window (min)",
  "editor.battery_invert": "Battery: positive means charging",
  "editor.grid_invert": "Grid: positive means export",
  "editor.ring_style": "Ring style",
  "editor.ring_single": "One ring",
  "editor.ring_double": "Two rings",
  "editor.help_ring_style": "The outer ring asks the same question over the whole day.",
  "editor.ring_clock": "Clock",
  "editor.meter_day": "Day strip",
  "editor.origin_style": "How the day bar is drawn",
  "editor.origin_shares": "Shares",
  "editor.origin_band": "Day band",
  "editor.help_origin_style": "The band puts the same sources on a time axis.",
  "editor.inner": "Behind the number",
  "editor.inner_icon": "A symbol for the mode",
  "editor.inner_load": "The day's consumption curve",
  "editor.inner_none": "Nothing",
  "editor.import_red": "Grid draw in red",
  "editor.help_import_red": "Ring, column and bar alike, for as long as it lasts.",
  "editor.clock_marks": "Sun and moon on the dial",
  "editor.help_clock_marks": "Noon at the top, midnight at the bottom.",
  "editor.ring_settings": "Ring",
  "editor.size": "Size of ring and column",
  "editor.size_auto": "Automatic",
  "editor.size_s": "Small",
  "editor.size_m": "Medium",
  "editor.size_l": "Large",
  "editor.help_size": "Automatic grows them when they have the card to themselves.",
  "editor.meter_settings": "Columns",
  "editor.center": "Centre value",
  "editor.help_center": "With a column beside it, keep the ring on the house.",
  "editor.center_dark": "Centre value without sun",
  "editor.help_center_dark": "Takes over once the sun is down.",
  "editor.center_power": "House power (kW)",
  "editor.center_autarky": "Self-supplied share (%)",
  "editor.center_production": "What the PV produces",
  "editor.center_surplus": "Available surplus",
  "editor.layout": "Placement of the values",
  "editor.layout_auto": "Beside when there is room",
  "editor.layout_beside": "Always beside",
  "editor.layout_below": "Always below",
  "editor.caption": "Label under the number",
  "editor.help_caption": "Free, produced, own power — or the house, which the icon already names.",
  "editor.facts": "Values beside the ring",
  "editor.facts_bars": "List with bars",
  "editor.facts_plain": "Plain list",
  "editor.facts_inline": "One line",
  "editor.facts_none": "Hidden",
  "editor.meter_scale": "Full deflection up (kW)",
  "editor.meter_scale_draw": "Full deflection down (kW)",
  "editor.help_meter_scale_draw": "0 uses three kilowatts, the band a house lives in.",
  "editor.meter_target": "Worth switching on (kW)",
  "editor.meter_steps": "Blocks per direction",
  "editor.help_meter_steps": "The night column counts hours instead.",
  "editor.meter_shows": "What it shows",
  "editor.shows_grid": "Grid exchange now",
  "editor.help_meter_shows": "The subject of the column. How it is drawn is the next question.",
  "editor.meter_style": "How it is drawn",
  "editor.meter_bar": "Continuous",
  "editor.meter_blocks": "Blocks",
  "editor.help_meter_scale": "0 takes the system's peak over the past year.",
  "editor.help_meter_target": "Only you know what is worth starting. 0 switches it off.",
  "editor.chart_settings": "Day chart",
  "editor.consumption": "Show consumption line",
  "editor.show_forecast": "Show forecast",
  "editor.chart_height": "Chart height",
  "editor.chart_area": "Curve",
  "editor.chart_bars": "Hourly bars",
  "editor.today_settings": "Today",
  "editor.money": "Show money",
  "editor.breakdown": "Split the balance",
  "editor.amortisation_corner": "Paid off, in the corner",
  "editor.origin_bar": "Day bar by origin",
  "editor.battery_out_today": "Battery output today",
  "editor.amortisation": "Paid off so far",
  "editor.stats": "Values shown",
  "editor.help_runtime": "The load is averaged over this many minutes.",
  "editor.help_house": "The only required entity."
};
const de: Table = {
  "card.name": "Power Origin",
  "card.description": "Woher der Strom im Haus kommt, wie der Tag lief, was er gebracht hat.",
  "state.gridfree": "Autark",
  "state.importing": "Netzbezug",
  "state.unknown": "Keine Daten",
  "state.unreachable": "Hausverbrauch meldet nichts:",
  "ring.caption_autarky": "AUTARKIE",
  "ring.caption_house": "HAUS",
  "ring.caption_until": "bis",
  "ring.source_battery": "Speicher",
  "ring.source_grid": "Netz",
  "ring.source_solar": "Sonne",
  "ring.caption_surplus": "FREI",
  "ring.caption_production": "ERZEUGT",
  "ring.no_surplus": "NICHTS FREI",
  "flow.to_house": "Ins Haus",
  "flow.to_battery": "In den Speicher",
  "flow.to_grid": "Ins Netz",
  "flow.from_solar": "Aus der Sonne",
  "flow.own": "Eigenstrom",
  "flow.from_battery": "Aus dem Speicher",
  "flow.from_grid": "Aus dem Netz",
  "meter.surplus": "Überschuss",
  "editor.meter_scope": "Was als Überschuss zählt",
  "editor.meter_scope_grid": "Nur Netz",
  "editor.meter_scope_all": "Netz und Speicher",
  "editor.help_meter_scope": "Nur Netz ist, was über den Zähler geht.",
  "editor.meter_today": "Tages-Extreme zeigen",
  "editor.help_meter_today": "Wie weit der Zeiger heute ausgeschlagen ist, in beide Richtungen.",
  "editor.columns": "Säulen neben dem Ring",
  "editor.columns_none": "Keine",
  "editor.columns_one": "Eine",
  "editor.columns_two": "Zwei",
  "editor.column_left": "Die linke Säule",
  "editor.column_right": "Die rechte Säule",
  "editor.meter_top": "Bestwert über der Säule",
  "editor.help_meter_top": "Ohne sie sagen die Kilowatt nicht, ob der Moment gut ist.",
  "editor.meter_marks": "Raus und rein an den Enden",
  "editor.help_meter_marks": "Zwei kleine Pfeile, damit klar ist, welches Ende was bedeutet.",
  "editor.meter_money": "Geld",
  "editor.meter_load": "Haus jetzt gegen den Tagesschnitt",
  "editor.meter_autarky": "Autarkie jetzt, von unten nach oben",
  "meter.earning": "Ertrag jetzt",
  "meter.costing": "Kosten jetzt",
  "meter.above": "über dem Tagesschnitt",
  "meter.below": "unter dem Tagesschnitt",
  "meter.usual": "gewöhnliche Stunde",
  "meter.autarky": "Autarkie jetzt",
  "editor.center_runtime": "Wie lange der Speicher reicht",
  "editor.center_money": "Geld je Stunde (€/h)",
  "ring.caption_earning": "VERDIENT",
  "ring.caption_costing": "KOSTET",
  "ring.caption_even": "AUSGEGLICHEN",
  "editor.ring_dayclock": "Uhr außen",
  "editor.inner_battery": "Der Ladestand als dünner Ring",
  "editor.night": "Der Ring bei Nacht",
  "editor.night_countdown": "Countdown",
  "editor.help_night": "Der äußere Ring wird zur Nacht, gefüllt so weit sie schon ist.",
  "ring.to_sun": "bis Sonne",
  "editor.tap": "Tippen auf den Ring",
  "editor.tap_entity": "Öffnet die Entität hinter der Zahl",
  "editor.tap_cycle": "Schaltet den Wert in der Mitte weiter",
  "editor.help_tap": "Weiter durch Haus, Autarkie und Geld; der Ring merkt sich, wo er stehen blieb.",
  "editor.sunrise_mark": "Sonne beim Stand zu Sonnenaufgang",
  "editor.help_sunrise_mark": "Nachts eine Sonne unter dem Balken, wo der Ladestand bei Sonnenaufgang stehen wird.",
  "editor.sunset_mark": "Mond beim Stand zu Sonnenuntergang",
  "editor.help_sunset_mark": "Tagsüber ein Mond unter dem Balken, wo der Ladestand bei Sonnenuntergang steht, wenn er nicht voll wird.",
  "editor.meter_battery": "Speicher",
  "editor.meter_night": "Die Nacht",
  "editor.meter_devices": "Geräte",
  "editor.meter_none": "Nichts",
  "editor.columns_scale": "Waage unter dem Ring",
  "editor.help_columns": "Die Waage legt die linke Säule flach unter den Ring.",
  "editor.import_switch": "Anhaltender Bezug schaltet die Säule um",
  "editor.help_import_switch": "Zwei Minuten Bezug schalten um, fünf ohne wieder zurück.",
  "meter.night": "die Nacht",
  "meter.at_sunrise": "bei Sonnenaufgang",
  "meter.grid_until_sun": "Netz bis Sonnenaufgang",
  "editor.battery_night": "Der Balken bei Nacht",
  "editor.autarky_colours": "Autarkie-Säule in drei Farben",
  "editor.help_autarky_colours": "Netz unter der Hälfte, Sonne bis achtzig Prozent, Speicher darüber.",
  "editor.animate": "Welle, solange der Speicher arbeitet",
  "editor.help_animate": "Zum Pol hin beim Laden, vom Pol weg beim Entladen.",
  "meter.held": "gehalten",
  "editor.forecast_hourly": "Prognose nach Stunden",
  "editor.help_forecast_hourly": "Solcasts „Prognose heute“ trägt sie in seinen Attributen. Mehrere, je Dachfläche eine, werden addiert.",
  "editor.forecast_bars": "Erwartete Stunden als Umrisse",
  "editor.help_forecast_bars": "Gestrichelte Umrisse; nach Sonnenuntergang der morgige Tag.",
  "editor.layers": "Netz und Speicher als Flächen",
  "editor.help_layers": "Stunde für Stunde, unter dem Tag.",
  "editor.best_day": "Bester Tag des Jahres dahinter",
  "editor.help_best_day": "Eine blasse Linie, an der sich heute messen lässt.",
  "editor.section_week": "Woche",
  "week.title": "Woche",
  "chart.best": "Bestwert",
  "editor.battery_in_today": "Speicherladung heute",
  "editor.extra_flow": "Heute geladen und abgegeben, mit den Zyklen",
  "editor.curve": "Ladestand als Kurve darunter",
  "editor.help_curve": "Gestrichelt weiter bis Sonnenaufgang oder bis voll.",
  "battery.flow": "geladen und abgegeben",
  "editor.meter_dark": "Ohne Sonne zeigt sie",
  "editor.help_meter_dark": "Was bis Sonnenaufgang an die Stelle der Säule tritt.",
  "editor.same": "Unverändert",
  "editor.night_dim": "Nachts dimmen (%)",
  "editor.help_night_dim": "Der Chip bleibt hell. Für das Panel an der Wand.",
  "editor.extra_sunrise": "Stand bei Sonnenaufgang",
  "meter.range_reaches": "reicht bis Sonnenaufgang",
  "chart.tomorrow": "morgen",
  "editor.forecast_tomorrow": "Prognose morgen",
  "meter.range_gap": "fehlen",
  "battery.at_sunrise": "bei Sonnenaufgang um",
  "meter.roof": "PV jetzt",
  "editor.meter_roof": "Was die PV jetzt macht, gegen ihren Bestwert heute",
  "meter.day": "heute nach Stunden",
  "meter.balance": "PV gegen Haus",
  "meter.spare": "PV übrig",
  "meter.short": "zugekauft",
  "editor.meter_balance": "PV und Haus jetzt",
  "meter.quiet": "kein Netzaustausch",
  "meter.draw": "Entnahme",
  "meter.charging": "in den Speicher",
  "meter.export": "ins Netz",
  "meter.import": "aus dem Netz",
  "meter.discharging": "aus dem Speicher",
  "meter.balanced": "ausgeglichen",
  "editor.compare": "Mit der Vorwoche vergleichen",
  "editor.help_compare": "Derselbe Wochentag vor einer Woche, blass hinter heute.",
  "devices.today": "heute",
  "editor.mode": "Zeitraum",
  "editor.mode_now": "Jetzt",
  "editor.mode_today": "Heute",
  "editor.help_mode": "Liest die Zähler, die das Energie-Dashboard je Gerät kennt.",
  "editor.window": "Fenster (Minuten)",
  "editor.help_window": "So lange gemittelt, damit ein Wasserkocher kein Fresser wird.",
  "devices.title": "Wohin",
  "devices.rest": "Rest",
  "devices.nowhere": "ohne Raum",
  "editor.section_devices": "Geräte",
  "editor.devices_settings": "Geräte",
  "editor.list": "Geräte (Leistungssensoren)",
  "editor.help_list": "Das Icon kommt vom Sensor in Home Assistant.",
  "editor.source": "Geräteliste",
  "editor.source_list": "Eigene Liste",
  "editor.source_energy": "Energie-Dashboard",
  "editor.help_source": "Folgt die Karte dem Dashboard, taucht ein dort neues Gerät binnen einer Stunde hier auf.",
  "editor.devices_head": "Überschrift zeigen",
  "editor.help_devices_head": "Das Wort und der Zeitraum über dem Block.",
  "editor.devices_colours": "Jedes Gerät in eigener Farbe",
  "editor.help_devices_colours": "Wie im Energie-Dashboard; sonst nur Helligkeit.",
  "editor.devices_rows": "Zeilen",
  "editor.devices_band": "Band",
  "editor.devices_icons": "Icons im Raster, mit Pegel",
  "devices.one": "Gerät",
  "devices.many": "Geräte",
  "editor.top": "Das größte als eigene Zeile",
  "editor.help_top": "Mit der Zeit, seit der es zieht, und was es heute gekostet hat.",
  "editor.spark": "Eine Linie je Gerät, letzte Stunde",
  "editor.help_spark": "Der Takt des Kühlschranks, die Rampe der Wärmepumpe.",
  "editor.device_icons": "Icons",
  "devices.since": "seit",
  "editor.month": "Der Monat neben dem Tag",
  "editor.help_month": "Klein neben dem Tageswert.",
  "editor.split": "Nicht gekauft und verkauft trennen",
  "editor.help_split": "Wie viel vom Tagesgeld Nicht-Kaufen war und wie viel Verkaufen.",
  "editor.payoff_year": "Das Jahr, in dem sie abbezahlt ist",
  "editor.help_payoff_year": "Aus dem amortisierten Anteil und dem Tempo dieses Jahres.",
  "editor.investment": "Was die Anlage gekostet hat (€)",
  "editor.help_investment": "Alles zusammen. Bei 0 liest die Karte den Betrag vom Amortisations-Sensor.",
  "money.not_bought": "nicht gekauft",
  "money.sold": "verkauft",
  "editor.card_settings": "Karte",
  "editor.head_settings": "Kopfzeile",
  "editor.chip_shows": "Der Chip sagt",
  "editor.chip_state": "Zustand",
  "editor.chip_autarky": "Die Autarkie des Tages",
  "chip.autarky": "autark",
  "editor.chip_alarm": "Anhaltender Bezug färbt den Chip rot",
  "editor.help_chip_alarm": "Nach zwei Minuten Bezug wird der Chip rot und trägt die Kilowatt.",
  "editor.head_price": "Der Bezugspreis neben dem Titel",
  "editor.help_head_price": "Grün unter dem Tagesmittel, rot darüber.",
  "editor.card_layout": "Form der Karte",
  "editor.layout_standard": "Standard",
  "editor.layout_wide": "Breit",
  "editor.layout_compact": "Kompakt",
  "editor.wide_from": "Breit ab (px)",
  "editor.help_wide_from": "Schmaler stapelt die Karte; unter 560 px in jedem Fall.",
  "editor.night_layout": "Sobald die Sonne unten ist",
  "editor.night_quiet": "Ruhig",
  "editor.help_night_layout": "Ruhig behält Ring, Speicher und eine Zeile zum Tag.",
  "compact.roof": "PV",
  "editor.head_sunbar": "Sonnenleiste unter dem Titel",
  "editor.help_head_sunbar": "Ein Bogen mit der Sonne, wo sie gerade steht, und nachts mit dem Mond.",
  "money.of": "von",
  "money.a_year": "im Jahr bei diesem Tempo",
  "editor.values": "Watt beschriften",
  "editor.group": "Zusammenfassen",
  "editor.group_device": "Je Gerät",
  "editor.group_area": "Je Raum",
  "editor.help_group": "Je Raum summiert die Geräte eines Raums, gelesen aus dem Geräteregister.",
  "editor.merge_icons": "Gleiche Symbole zusammenfassen",
  "editor.help_merge_icons": "Zwei Kühlschränke werden ein Symbol mit der Summe; die Namen stehen im Tooltip.",
  "editor.limit": "Höchstens",
  "editor.help_limit": "Zeilen und Band benennen so viele und falten den Rest; Icons zeigen nicht mehr als das.",
  "editor.threshold": "Benannt ab (W)",
  "editor.help_threshold": "Kleineres fällt in den Rest — sonst stünden neun Kühlschränke da.",
  "chart.title": "Heute",
  "chart.now": "jetzt",
  "chart.roof_now": "PV jetzt",
  "chart.produced": "kWh erzeugt",
  "chart.consumed": "verbraucht",
  "chart.forecast": "erwartet",
  "chart.shortfall": "unter Prognose",
  "chart.snow": "Schnee am Dach?",
  "editor.reserve_line": "Reserve auf dem Balken markieren",
  "editor.extra": "Zweiter Wert neben dem Balken",
  "editor.extra_none": "Keiner",
  "editor.extra_range": "Tiefst- und Höchststand heute",
  "editor.extra_cycles": "Zyklen heute",
  "editor.extra_saved": "Heute nicht gekauft",
  "editor.extra_given": "Heute abgegeben",
  "editor.help_extra": "Der Balken gibt dafür Breite ab.",
  "battery.range": "tiefst bis höchst",
  "battery.cycles": "Zyklen",
  "battery.saved": "nicht gekauft",
  "battery.given": "abgegeben",
  "editor.percent": "Ladestand als Zahl zeigen",
  "battery.title": "Speicher",
  "battery.full": "Voll",
  "battery.charging": "lädt mit",
  "battery.delivering": "liefert",
  "battery.full_at": "Voll um",
  "battery.full_about": "Voll gegen",
  "battery.full_between": "Voll zwischen",
  "battery.and": "und",
  "battery.not_full_today": "Heute nicht voll",
  "battery.today_up_to": "Heute bis",
  "editor.full_from": "Wann er voll ist",
  "editor.full_rate": "Aus der Laderate gerade",
  "editor.full_forecast": "Aus der Prognose nach Stunden",
  "editor.help_full_from": "Die Laderate sieht den Abend nicht, die Prognose schon.",
  "editor.palette": "Farben",
  "editor.palette_standard": "Standard",
  "editor.palette_traffic": "Ampel",
  "editor.palette_safe": "Farbsehschwäche",
  "editor.palette_muted": "Gedeckt",
  "editor.help_palette": "Ein Satz für die ganze Karte. Standard: Sonne gold, Speicher grün, Netz blau. Ampel: gelb, orange, rot. Farbsehschwäche: bernstein, blau, magenta. Gedeckt: dieselben drei, leiser.",
  "editor.font": "Zahlen",
  "editor.font_mono": "Monospace",
  "editor.font_system": "Home Assistant",
  "editor.help_font": "Monospace hält eine wechselnde Zahl an Ort und Stelle; die Schrift von Home Assistant passt zu den Karten drumherum.",
  "battery.lasts_until": "Reicht bis",
  "battery.at_reserve": "Auf Reserve",
  "battery.sunrise_tight": "Knapp bis Sonnenaufgang",
  "battery.sunrise_ok": "Reicht bis Sonnenaufgang",
  "battery.sunrise_easy": "Locker bis Sonnenaufgang",
  "battery.remaining": "übrig",
  "battery.stored": "gespeichert",
  "battery.resting": "Bereit",
  "today.earned": "€ verdient",
  "today.paid": "€ gezahlt",
  "today.exported_money": "eingespeist",
  "today.imported_money": "bezogen",
  "stat.peak": "PV-Spitze",
  "stat.autarky": "Autarkie",
  "stat.export": "Eingespeist",
  "stat.import": "Bezogen",
  "stat.solar": "Erzeugt",
  "stat.house": "Verbraucht",
  "stat.forecast": "Noch erwartet",
  "stat.amortisation": "Amortisiert",
  "error.no_house": "Bitte den Sensor für den Hausverbrauch angeben.",
  "editor.title": "Titel",
  "editor.tap_action": "Klick auf eine Zahl",
  "editor.help_tap_action": "Standardmäßig öffnet eine Zahl die Entität, aus der sie stammt.",
  "editor.chip": "Status-Chip",
  "editor.chip_gridfree": "Nur wenn netzfrei",
  "editor.chip_always": "Immer",
  "editor.chip_never": "Nie",
  "editor.help_chip": "Netzfrei behält es für den Zustand, der auffallen soll.",
  "editor.text_scale": "Textgröße",
  "editor.help_title": "Nach der Anlage benennen. Leer gelassen zeigt die Karte keine Überschrift.",
  "editor.help_text_scale": "Etwa 1,2 für ein Tablet, das man aus einigen Metern liest.",        "editor.entities": "Entitäten",
  "editor.house": "Hausverbrauch",
  "editor.solar": "PV-Leistung",
  "editor.battery": "Speicherleistung",
  "editor.battery_soc": "Ladestand",
  "editor.grid": "Netzleistung",
  "editor.solar_today": "Heute erzeugt",
  "editor.house_today": "Heute verbraucht",
  "editor.export_today": "Heute eingespeist",
  "editor.import_today": "Heute bezogen",
  "editor.forecast": "Prognose Rest",
  "editor.help_cost_today": "Leer lassen, dann ist es Erlös minus Kosten, hier gerechnet.",
  "editor.help_cost_sides": "Leer ist es Preis mal Energie, was bei einem Fixtarif stimmt.",
  "editor.help_price": "Ein fester Preis je Kilowattstunde.",
  "editor.cost_today": "Tagesbilanz",
  "editor.cost_export_today": "Erlös Einspeisung heute",
  "editor.cost_import_today": "Kosten Netzbezug heute",
  "editor.price_import": "Bezugspreis",
  "editor.price_export": "Einspeisepreis",
  "editor.sections": "Blöcke",
  "editor.order": "Reihenfolge",
  "editor.help_order": "Wählen, dann ziehen; der Rest folgt.",
  "editor.section_ring": "Ring",
  "editor.section_chart": "Tagesverlauf",
  "editor.section_battery": "Speicher",
  "editor.section_today": "Heute",
  "editor.battery_settings": "Speicher",
  "editor.capacity": "Kapazität (Wh)",
  "editor.reserve": "Reserve (%)",
  "editor.style": "Darstellung",
  "editor.style_segments": "Segmente",
  "editor.style_solid": "Durchgehend",
  "editor.style_bar": "Balken ohne Gehäuse",
  "editor.segments": "Anzahl Segmente",
  "editor.help_segments": "Null zeichnet eines je Kilowattstunde — dann sind die Blöcke abzählbar.",
  "editor.runtime": "Restzeit anzeigen",
  "editor.runtime_window": "Mittelung (Minuten)",
  "editor.battery_invert": "Speicher: positiv bedeutet laden",
  "editor.grid_invert": "Netz: positiv bedeutet einspeisen",
  "editor.ring_style": "Ring-Stil",
  "editor.ring_single": "Ein Ring",
  "editor.ring_double": "Zwei Ringe",
  "editor.help_ring_style": "Der äußere Ring stellt dieselbe Frage über den ganzen Tag.",
  "editor.ring_clock": "Uhr",
  "editor.meter_day": "Tagesstreifen",
  "editor.origin_style": "Wie der Tagesbalken gezeichnet wird",
  "editor.origin_shares": "Anteile",
  "editor.origin_band": "Tagesband",
  "editor.help_origin_style": "Das Band stellt dieselben Quellen auf eine Zeitachse.",
  "editor.inner": "Hinter der Zahl",
  "editor.inner_icon": "Ein Symbol zum Modus",
  "editor.inner_load": "Die Verbrauchskurve des Tages",
  "editor.inner_none": "Nichts",
  "editor.import_red": "Netzbezug in Rot",
  "editor.help_import_red": "Ring, Säule und Balken, solange es dauert.",
  "editor.clock_marks": "Sonne und Mond am Zifferblatt",
  "editor.help_clock_marks": "Mittag oben, Mitternacht unten.",
  "editor.ring_settings": "Der Ring",
  "editor.size": "Größe von Ring und Säule",
  "editor.size_auto": "Automatisch",
  "editor.size_s": "Klein",
  "editor.size_m": "Mittel",
  "editor.size_l": "Groß",
  "editor.help_size": "Automatisch lässt sie wachsen, wenn sie die Karte für sich haben.",
  "editor.meter_settings": "Säulen",
  "editor.center": "Wert in der Mitte",
  "editor.help_center": "Mit Säule daneben den Ring beim Haus lassen.",
  "editor.center_dark": "Wert in der Mitte ohne Sonne",
  "editor.help_center_dark": "Übernimmt, sobald die Sonne unten ist.",
  "editor.center_power": "Hausverbrauch (kW)",
  "editor.center_autarky": "Autarkie (%)",
  "editor.center_production": "PV-Erzeugung",
  "editor.center_surplus": "Freier Überschuss",
  "editor.layout": "Anordnung der Werte",
  "editor.layout_auto": "Daneben, wenn Platz ist",
  "editor.layout_beside": "Immer daneben",
  "editor.layout_below": "Immer darunter",
  "editor.caption": "Beschriftung unter der Zahl",
  "editor.help_caption": "Frei, erzeugt, Eigenstrom — oder das Haus, das schon das Symbol benennt.",
  "editor.facts": "Werte neben dem Ring",
  "editor.facts_bars": "Liste mit Balken",
  "editor.facts_plain": "Schlichte Liste",
  "editor.facts_inline": "Einzeilig",
  "editor.facts_none": "Ausgeblendet",
  "editor.meter_scale": "Vollausschlag oben (kW)",
  "editor.meter_scale_draw": "Vollausschlag unten (kW)",
  "editor.help_meter_scale_draw": "Bei 0 drei Kilowatt, der Bereich, in dem ein Haus lebt.",
  "editor.meter_target": "Lohnt sich ab (kW)",
  "editor.meter_steps": "Blöcke je Richtung",
  "editor.help_meter_steps": "Die Nacht-Säule zählt stattdessen Stunden.",
  "editor.meter_shows": "Was sie zeigt",
  "editor.shows_grid": "Netzaustausch jetzt",
  "editor.help_meter_shows": "Das Thema der Säule. Wie sie gezeichnet wird, ist die nächste Frage.",
  "editor.meter_style": "Wie sie gezeichnet ist",
  "editor.meter_bar": "Stufenlos",
  "editor.meter_blocks": "Blöcke",
  "editor.help_meter_scale": "Bei 0 die Jahresspitze der Anlage.",
  "editor.help_meter_target": "Was sich zu starten lohnt, weißt nur du. 0 schaltet es aus.",
  "editor.chart_settings": "Tagesverlauf",
  "editor.consumption": "Verbrauchslinie anzeigen",
  "editor.show_forecast": "Prognose anzeigen",
  "editor.chart_height": "Höhe des Diagramms",
  "editor.chart_area": "Kurve",
  "editor.chart_bars": "Stundenbalken",
  "editor.today_settings": "Heute",
  "editor.money": "Geld anzeigen",
  "editor.breakdown": "Bilanz aufschlüsseln",
  "editor.amortisation_corner": "Amortisiert, in der Ecke",
  "editor.origin_bar": "Tagesbalken nach Herkunft",
  "editor.battery_out_today": "Speicherabgabe heute",
  "editor.amortisation": "Bisher amortisiert",
  "editor.stats": "Angezeigte Werte",
  "editor.help_runtime": "Über so viele Minuten wird die Last gemittelt.",
  "editor.help_house": "Die einzige Pflichtangabe."
};
export const TRANSLATIONS: Record<string, Table> = { en, de };
export function baseLanguage(locale: string | undefined): string {
  const tag = String(locale ?? "").toLowerCase();
  const base = tag.split(/[-_]/)[0];
  return base in TRANSLATIONS ? base : "en";
}
export function localize(key: string, locale?: string): string {
  const table = TRANSLATIONS[baseLanguage(locale)];
  return table[key] ?? en[key] ?? key;
}